### ISSUE TITLE
Music v0.17.2 interferes delete on the Files app

### ISSUE THREAD

**Issue by AlexShelest** [owncloud/music#798]
NC 19.0.4

After updating music app to 0.17.2, delete button not working.

Uncaught TypeError: _.pluck is not a function
    _onClickDeleteSelected https://cloudhelpme.ru/js/files/merged-index.js?v=54e31561-37:4951
    multiSelectMenuClick https://cloudhelpme.ru/js/files/merged-index.js?v=54e31561-37:4386
    _onClickAction https://cloudhelpme.ru/js/files/merged-index.js?v=54e31561-37:7806
    dispatch https://cloudhelpme.ru/core/js/dist/main.js?v=54e31561-37:1
    handle https://cloudhelpme.ru/core/js/dist/main.js?v=54e31561-37:1

**Comment by paulijar** [comment]
Thanks for the report. Just to clarify, the problem case is when deleting a file within the Files app.

The problem is that the lodash.js library bundled with the Music app is leaked to the global namespace even though that is not supposed to happen. In the global namespace, it shadows the underscore.js library which is used by the Files app. As lodash.js is only partially API-compatible with underscore.js, the Files app can't function correctly with the unexpected library.

Now why this happens, is a bit of a mystery. But it *seems* that the problem happens when I build the webpack bundle using Cygwin (as I did with the release package). And the problem doesn't happen if I build the bundle using the Windows Power Shell. This kind of difference is quite surprising as the bundle built on Cygwin seems to otherwise work just fine.

**Comment by pianshanchou** [comment]
I also encountered the same problem, new folder and delete file can not be used, need to refresh to get results. It's a great program, but it's not going to be used for now.

**Comment by paulijar** [comment]
I was busy yesterday but I should be able to make a fix release today or latest tomorrow.

**Comment by paulijar** [comment]
The Music v0.17.3 fixing this issue has now been published.

**Comment by pianshanchou** [comment]
Fortunately, I can use it again! Great work!

**Comment by dusnm** [comment]
Thanks! I was wondering why it wasn't working, but since I use the Music app heavily I decided to just stick with the problem until it was fixed. Awesome work guys!
